#!/usr/bin/env python3
"""Embed supplied MIDI timing and verbatim stanza text; runtime is integer-only."""
import argparse
import bisect
from collections import Counter
from fractions import Fraction
import json
from pathlib import Path
from midi import parse_midi

ROOT=Path(__file__).resolve().parents[1]
# The supplied MIDI's sung melody is track 9/channel 8 (zero-based 9/7).
VOICE=(9,7)
# Page boundaries follow the repeated verse/chorus phrases in this arrangement.
CUES=[4800,24000,45600,64800,86400,105600]


def generate():
    division,tempos,lanes,names,end=parse_midi(ROOT/"assets/want_you_gone.mid")
    if VOICE not in lanes: raise ValueError("Expected supplied vocal melody lane")
    tempo_map=dict(tempos);starts=sorted(tempo_map);times=[Fraction(0)]
    for a,b in zip(starts,starts[1:]):
        times.append(times[-1]+Fraction((b-a)*tempo_map[a],division*1000))
    def ms(tick):
        i=bisect.bisect_right(starts,tick)-1
        return int(times[i]+Fraction((tick-starts[i])*tempo_map[starts[i]],division*1000))
    events={}
    for lane,notes in lanes.items():
        for tick,pitch,on in notes: events.setdefault(tick,[]).append((lane,pitch,on))
    events.setdefault(end,[])
    active={lane:Counter() for lane in lanes};segments=[];previous=0
    for tick,changes in sorted(events.items()):
        now=ms(tick)
        pitches=active[VOICE]
        if not pitches:
            pitches=[p for values in active.values() for p in values]
        pitch=max(pitches,default=None)
        hz=0 if pitch is None else round(440*2**((pitch-69)/12))
        if now>previous:
            if segments and segments[-1][0]==hz:
                segments[-1]=(hz,segments[-1][1]+now-previous)
            else: segments.append((hz,now-previous))
        for lane,pitch,on in changes:
            if on: active[lane][pitch]+=1
            elif active[lane][pitch]:
                active[lane][pitch]-=1
                if not active[lane][pitch]: del active[lane][pitch]
        previous=now
    raw=(ROOT/"assets/lyrics.txt").read_text().replace("\r\n","\n")
    pages=[part.strip() for part in __import__("re").split(r"\n\s*\n",raw.strip())]
    if len(pages)!=6: raise ValueError("Expected six supplied stanzas")
    output=["/* Generated by tools/generate.py from the bundled user attachments. */",
            "#ifndef GLADOS_DATA_H","#define GLADOS_DATA_H",
            "typedef struct { uint32_t hz, ms; } glados_note;",
            "typedef struct { const char *text; uint32_t start, typing_ms; unsigned len, row, col; } glados_stanza;",
            "static const glados_note glados_notes[] = {"]
    output.extend(f"    {{{hz}u,{duration}u}}," for hz,duration in segments)
    output.append("};")
    output.append("static const glados_stanza glados_stanzas[] = {")
    for i,page in enumerate(pages):
        page.encode("ascii") # fail explicitly, do not drop/replace supplied lyrics
        lines=page.splitlines();width=max(map(len,lines))
        if width>76 or len(lines)>21: raise ValueError("Stanza does not fit VGA")
        finish=CUES[i+1] if i+1<len(CUES) else ms(end)
        typing=finish-CUES[i]-2500
        output.append("    {"+json.dumps(page)+f",{CUES[i]}u,{typing}u,"
                      f"{len(page)}u,{(25-len(lines))//2}u,{(80-width)//2}u"+"},")
    output+=["};",f"#define GLADOS_DURATION {ms(end)}u","#endif",""]
    return "\n".join(output)


if __name__=="__main__":
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check",action="store_true")
    args=parser.parse_args();text=generate();out=ROOT/"data.h"
    if args.check:
        if out.read_text()!=text: raise SystemExit("Stale embedded assets: run tools/generate.py")
        print("PASS: embedded notes/tempo/stanzas match supplied assets")
    else:
        out.write_text(text)
        print("Generated",out)
