#!/usr/bin/env python3
"""Embed QBasic PLAY melody and maintained stanzas; runtime is integer-only."""
import argparse
import json
from pathlib import Path
import re
from qbasic_music import convert

ROOT=Path(__file__).resolve().parents[1]
# Existing presentation is frozen separately; regenerating music must not
# reintroduce hidden headings or change any lyric/layout/timing fields.
LYRIC_END=136806


def stanza_presentation():
    presentation=(ROOT/"assets/stanzas.inc").read_text().rstrip()
    rows=re.findall(r'\{("(?:[^"\\]|\\.)*"),(\d+)u,(\d+)u,(\d+)u,(\d+)u,(\d+)u\}',presentation)
    if not rows:
        raise ValueError("No maintained GLADOS stanzas found")
    for index,(literal,start,typing,length,row,col) in enumerate(rows,1):
        text=json.loads(literal)
        # These maintained literals are ASCII, so character and C byte counts agree.
        actual=len(text.encode("ascii"))
        if "\0" in text or int(length)!=actual:
            raise ValueError(f"Stanza {index}: stored length {length} does not match text length {actual}")
    return presentation


def generate():
    segments,duration=convert((ROOT/"assets/melody.bas").read_text(encoding="cp437"))
    output=["/* Generated by tools/generate.py from the bundled user attachments. */",
            "#ifndef GLADOS_DATA_H","#define GLADOS_DATA_H",
            "typedef struct { uint32_t hz, ms; } glados_note;",
            "typedef struct { const char *text; uint32_t start, typing_ms; unsigned len, row, col; } glados_stanza;",
            "static const glados_note glados_notes[] = {"]
    output.extend(f"    {{{hz}u,{duration}u}}," for hz,duration in segments)
    output.append("};")
    output.append(stanza_presentation())
    output+=[f"#define GLADOS_DURATION {max(duration,LYRIC_END)}u","#endif",""]
    return "\n".join(output)


if __name__=="__main__":
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check",action="store_true")
    args=parser.parse_args();text=generate();out=ROOT/"data.h"
    if args.check:
        if out.read_text()!=text: raise SystemExit("Stale embedded assets: run tools/generate.py")
        print("PASS: QBasic melody and preserved stanza presentation match bundled assets")
    else:
        out.write_text(text)
        print("Generated",out)
