#!/usr/bin/env python3
"""
cmake/bin2header.py — convert a binary file to a C uint8_t array header.

Usage: python3 bin2header.py <input.bin> <array_name> <output.h>

Generated header exposes:
  static const uint8_t <array_name>[N];
  static const uint32_t <array_name>_size;
"""
import sys

def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <input.bin> <array_name> <output.h>",
              file=sys.stderr)
        sys.exit(1)

    in_path, array_name, out_path = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(in_path, 'rb') as f:
        data = f.read()

    lines = [
        "/* Auto-generated by cmake/bin2header.py — do not edit. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"static const uint8_t {array_name}[] = {{",
    ]

    for i, byte in enumerate(data):
        if i % 16 == 0:
            lines.append("    ")
        lines[-1] += f"0x{byte:02X},"
        if i % 16 != 15:
            lines[-1] += " "
        else:
            lines[-1] = lines[-1].rstrip()

    lines.append("};")
    lines.append(f"static const uint32_t {array_name}_size = {len(data)};")
    lines.append("")

    with open(out_path, 'w') as f:
        f.write("\n".join(lines))

    print(f"[bin2header] {in_path} → {out_path}  ({len(data)} bytes, "
          f"array '{array_name}')")

if __name__ == "__main__":
    main()
