/*
 * Generated by build.sh and Willburd the Setup Wizard.
 * Re-run build.sh to change this hardware profile.
 */
#ifndef INTEILIDOS_GENERATED_CONFIG_H
#define INTEILIDOS_GENERATED_CONFIG_H

#define CONFIG_PROFILE_NAME "Generic 1990s PC"
#define CONFIG_CPU_CLASS 3
#define CONFIG_RAM_MB 16
#define CONFIG_BOOT_MEDIA 3

#define CONFIG_ENABLE_PS2_KEYBOARD 1
#define CONFIG_ENABLE_USB_KEYBOARD 0
#define CONFIG_ENABLE_PCI 0
#define CONFIG_ENABLE_PCI_IDE 0
#define CONFIG_ENABLE_AHCI 0
#define CONFIG_ENABLE_ATA 1
#define CONFIG_ENABLE_ATAPI_CDROM 1
#define CONFIG_ENABLE_FLOPPY 1
#define CONFIG_AUDIO_MODE 0
#define CONFIG_TIMER_HZ 1000

#define CONFIG_AUDIO_NONE 0
#define CONFIG_AUDIO_AC97 1
#define CONFIG_AUDIO_HDA 2
#define CONFIG_AUDIO_AUTO 3

#define CONFIG_CPU_386 3
#define CONFIG_CPU_486 4
#define CONFIG_CPU_PENTIUM 5
#define CONFIG_CPU_P6 6

#define CONFIG_BOOT_FLOPPY 1
#define CONFIG_BOOT_CDROM 2
#define CONFIG_BOOT_BOTH 3

#if !CONFIG_ENABLE_PS2_KEYBOARD && !CONFIG_ENABLE_USB_KEYBOARD
#error "At least one keyboard driver must be enabled"
#endif

#if CONFIG_ENABLE_USB_KEYBOARD && !CONFIG_ENABLE_PCI
#error "UHCI USB keyboard support requires PCI probing"
#endif

#if CONFIG_ENABLE_AHCI && !CONFIG_ENABLE_PCI
#error "AHCI support requires PCI probing"
#endif

#endif
