static const glados_stanza glados_stanzas[] = {
    {"\nWell, here we are again\nIt's always such a pleasure\nRemember when you tried to kill me twice?\nOh how we laughed and laughed\nExcept I wasn't laughing\nUnder the circumstances\nI've been shockingly nice",5400u,17300u,199u,8u,19u},
    {"\nYou want your freedom? Take it\nThat's what I'm counting on\nI used to want you dead\nBut now, I only want you gone",25200u,19400u,113u,10u,25u},
    {"\nShe was a lot like you\nMaybe not quite as heavy\nNow little Caroline is in here, too\nOne day, they woke me up\nSo, I could live forever\nIt's such a shame the same\nWill never happen to you",47100u,17300u,186u,8u,22u},
    {"\nYou've got your short sad life left\nThat's what I'm counting on\nI'll let you get right to it\nNow, I only want you gone",66900u,18800u,119u,10u,22u},
    {"\nGoodbye my only friend\nOh, did you think I meant you?\nThat would be funny\nIf it weren't so sad\nWell you have been replaced\nI don't need anyone now\nWhen I delete you maybe\nI'll stop feeling so bad",88200u,17300u,196u,8u,25u},
    {"\nGo make some new disaster\nThat's what I'm counting on\nYou're someone else's problem\nNow, I only want you gone\nNow, I only want you gone\nNow, I only want you gone",108000u,26306u,162u,9u,25u},
};
