#!/usr/bin/env python3
"""
wav_to_pcm.py  --  WAV → embedded kernel PCM
Usage: wav_to_pcm.py <input.wav> <symbol_name> <output.c>

Reads a standard PCM WAV file, downsamples it to 8000 Hz mono 8-bit
unsigned PCM, and writes a C source file containing:

    const uint32_t <symbol_name>_size;   /* number of samples */
    const uint8_t  <symbol_name>[];      /* raw PCM bytes     */

These symbols are referenced directly by the easter-egg players in
ibmrally.c and daisy.c.  The data lives in .rodata and is loaded into
the kernel binary — no GRUB modules or runtime disk access required.
"""

import struct
import sys
import os

TARGET_HZ = 8000   # output sample rate


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)

    wav_path, symbol, out_path = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(wav_path, 'rb') as f:
        wav = f.read()

    # ---- Validate RIFF/WAVE header -----------------------------------------
    if wav[:4] != b'RIFF' or wav[8:12] != b'WAVE':
        sys.exit(f"error: {wav_path} is not a valid WAV file")

    channels    = struct.unpack_from('<H', wav, 22)[0]
    sample_rate = struct.unpack_from('<I', wav, 24)[0]
    bps         = struct.unpack_from('<H', wav, 34)[0]

    if bps not in (8, 16):
        sys.exit(f"error: unsupported bit depth {bps} in {wav_path}")
    if channels == 0:
        sys.exit(f"error: zero channels in {wav_path}")

    # ---- Find 'data' chunk --------------------------------------------------
    pcm_raw = None
    pos = 12
    while pos + 8 <= len(wav):
        cid = wav[pos:pos+4]
        csz = struct.unpack_from('<I', wav, pos+4)[0]
        if cid == b'data':
            pcm_raw = wav[pos+8 : pos+8+csz]
            break
        pos += 8 + csz

    if pcm_raw is None:
        sys.exit(f"error: no 'data' chunk found in {wav_path}")

    # ---- Resample to TARGET_HZ mono 8-bit unsigned --------------------------
    bytes_per_frame = (bps // 8) * channels
    total_frames    = len(pcm_raw) // bytes_per_frame
    step            = sample_rate / TARGET_HZ   # source frames per output sample

    output = bytearray()
    pos_f  = 0.0

    while pos_f < total_frames:
        idx      = int(pos_f)
        byte_off = idx * bytes_per_frame
        nch      = min(channels, 2)          # mix at most 2 channels

        if bps == 16:
            acc = 0
            for ch in range(nch):
                acc += struct.unpack_from('<h', pcm_raw, byte_off + ch * 2)[0]
            mono = acc // nch
            u8   = (mono + 32768) >> 8       # signed 16-bit → unsigned 8-bit
        else:                                # bps == 8, unsigned samples
            acc = sum(pcm_raw[byte_off + ch] for ch in range(nch))
            u8  = acc // nch

        output.append(max(0, min(255, u8)))
        pos_f += step

    # ---- Emit C source -------------------------------------------------------
    name = os.path.basename(wav_path)
    duration = len(output) / TARGET_HZ

    with open(out_path, 'w') as f:
        f.write(f'/* Auto-generated by wav_to_pcm.py — DO NOT EDIT */\n')
        f.write(f'/* Source : {name}  ({sample_rate} Hz, {bps}-bit, {channels} ch) */\n')
        f.write(f'/* Output : {TARGET_HZ} Hz, 8-bit unsigned mono, {len(output)} bytes'
                f' ({duration:.1f} s) */\n\n')
        f.write('#include <stdint.h>\n\n')
        f.write(f'const uint32_t {symbol}_size = {len(output)}u;\n\n')
        f.write(f'const uint8_t {symbol}[] = {{\n')

        ROW = 24    # bytes per line — wider rows = fewer lines = faster GCC parse
        for i, byte in enumerate(output):
            if i % ROW == 0:
                f.write('    ')
            f.write(f'0x{byte:02X}')
            if i < len(output) - 1:
                f.write(',')
            if i % ROW == ROW - 1 or i == len(output) - 1:
                f.write('\n')
            else:
                f.write(' ')

        f.write('};\n')

    print(f"  {name}: {total_frames} frames → {len(output)} bytes"
          f" ({duration:.1f} s @ {TARGET_HZ} Hz)  →  {out_path}")


if __name__ == '__main__':
    main()
